<?php require("connection.php");?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>




<title>Welcome to patient Rights</title>




<link rel="stylesheet" type="text/css" href="css/style.css" />

<link rel="stylesheet" type="text/css" href="css/style_cf.css" />

<link rel="stylesheet" type="text/css" href="css/prettyPhoto.css" media="screen" />



 

<script type='text/javascript' src='js/jquery.js?ver=1.4.2'></script>

<script type="text/javascript" src="js/jquery-ui-1.5.2.packed.js"></script>

<script type="text/javascript" src="js/jquery.easing.1.1.1.js"></script>

<script type="text/javascript" src="js/jquery.cycle.all.min.js"></script>

<script type="text/javascript" src="js/jquery.validate.js"></script>

<script type="text/javascript" src="js/jquery.form.js"></script>

<script type="text/javascript" src="js/jquery.prettyPhoto.js"></script>

<script type="text/javascript" src="js/cufon.js"></script>   

<script type="text/javascript" src="js/anivers_400.font.js"></script>   

<script type="text/javascript" src="js/script.js"></script>



</head>

<body>



 

<div id="container">

<!-- header -->

<?php include("header.php");?>

<!-- /header -->





<div id="container1">

<div id="container2">

<div id="container3">    

    <div class="page_curv_top png"></div>

    <div class="content_con png">

<?php include("banner_image_front.php");?>
        <div class="content_con2">

            <!-- left side content -->

            <div class="content">                

					<div class="box single">

					 

					    					    <!-- box title-->
												<?php $sql="select * from pages where id='7'";
						$query=mysql_query($sql);
						$fetch=mysql_fetch_assoc($query);?>

					    					    <h3><a href="#" title="" ><?php echo $fetch['name'];?></a></h3>

					    					    					    

					    					    

						     
<div class="imgarea"><a href="#" title="" ><img src="page_image/<?php echo $fetch['image'];?>" width="300px" height="300px" alt="" class="alignleft featured_image preload png" /></a></div>
						    					        

						<p>
						
						<?php echo substr($fetch['description'],0,450);?> 
</p>	

								

						<a href="page_description.php?id=<?php echo $fetch['id'];?>" class="read_more" title="">earn more</a>

											    					</div>

					<div class="box small">

					 
<div class="m1">
        <h4>How May I Assist You</h4>
		<?php $sql="select * from confi";
		$mm=mysql_query($sql);
		$fe=mysql_fetch_assoc($mm);?>
        <img src="confi_image/<?php echo $fe['image'];?>" align="left" width="92" height="139" style="margin-right:25px;" />
        <p><?php echo $fe['phone'];?></p>
        <p><?php echo $fe['phone2'];?></p>
        <span>E-Mail :-<a href="#"><?php echo $fe['email'];?></a></span>
        </div>											    					
</div>

					<div class="box small">

					 

					    					    <!-- box title-->
<?php $sql="select * from pages where id='27'";
						$query=mysql_query($sql);
						$fetch=mysql_fetch_assoc($query);?>				        

					    					    <h4><a href="#" title="" ><?php echo $fetch['name'];?></a></h4>						

					    					    					    

					    					    

						    	
						<p><?php echo $fetch['description'];?></p>	

								

						<a href="page_description.php?id=<?php echo $fetch['id'];?>" class="read_more" title="" >latest works</a>

											    					</div>

					

				<!-- /box -->

	

	

	  

            </div>            <!-- / left side content -->

            

	                <!-- side bar -->

<?php include("achive.php")?>

            <!-- / side bar -->

	    	    

            <div class="clear"></div>

        </div>	



</div>

</div>

</div>                                          

</div>

<!-- footer -->

	
	<?php include("footer.php");?>

<!-- /footer -->

</div>

</body>

</html>
<!-- Dynamic page generated in 1.437 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2012-07-14 03:17:53 -->
<!-- super cache -->